### ISSUE TITLE
Some API routes have hard coded responses

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client-c12#16]
Lazy developers didn't finish some of the API routes so they're hard coded to respond with preset data. This just won't do.

**Comment by angustownsley** [comment]
The endpoints with hard coded responses have been identified as **Posts** and **Logs**.

Both endpoints are currently lacking a domain layer, so one will need to be created for each. Once a domain is created, each controller will need to be updated to use it.
Posts Endpoints:
 /posts POST:
Request Body:
```
{
  "content": "string"
}
```

Domain must return the newly created post's ID and content.

Response:
```
 {
  "status": "string",
  "data": {
    "post": {
      "id": 0,
      "content": "string"
    }
  }
}
```

/posts GET:
Request Body:
`{}`

Domain must return an array containing all posts and their authors. The authors password must not be returned.

Response
```
{
  "status": "string",
  "data": {
    "posts": [
      {
        "id": 0,
        "content": "string",
        "createdAt": "string",
        "updatedAt": "string",
        "author": {
          "id": 0,
          "cohortId": 0,
          "role": "string",
          "firstName": "string",
          "lastName": "string",
          "bio": "string",
          "githubUrl": "string",
          "profileImageUrl": "string"
        }
      }
    ]
  }
}
```

Logs Endpoint:
/logs POST:
Request Body:
```
{
  "date": "string",
  "cohortId": 0,
  "lines": [
    {
      "content": "string"
    }
  ]
}
```
Domain must return the newly created logs ID, cohortId, date, author, and all lines with their IDs and content.

Response
```
{
  "status": "string",
  "data": {
    "log": {
      "id": 0,
      "cohortId": 0,
      "date": "string",
      "author": {
        "id": 0,
        "firstName": "string",
        "lastName": "string"
      },
      "lines": [
        {
          "id": 0,
          "content": "string"
        }
      ]
    }
  }
}
```

**DATABASE CHANGES**

There are also some minor Database changes, 
Profile: A profileImageUrl column should be added to the entity

profileImageUrl: String | null

Post: createdAt and updatedAt columns must be added to the entity.

createdAt: DateTime @default(NOW)
updatedAt: DateTime @updateAt

**Controllers**

Once a domain is created, each controller will need to be updated.

Ensure each controller has appropriate error handling


**Documentation**

Controller changes must be reflected in the documentation.

**Comment by angustownsley** [comment]
Upon review, this will be split into separate tickets.
