### ISSUE TITLE
Registration & Creating a Profile

### ISSUE THREAD

**Issue by vherus** [boolean-uk/team-dev-client-c12#17]
Epic: https://github.com/boolean-uk/team-dev-client-c12/issues/1

**Details**

`POST /users`
Update the create user endpoint to include validation and return the correct error messages.

**API Request & Response Samples**

POST BODY

- The required fields are all strings (see further requirements below on validation): email and password
- The optional fields are all strings: firstName, lastName, biography, githubUrl
- Sending a POST request without the required fields should result in 400 error
- Sending a POST with optional fields should result in the optional values being written; however, if the optional fields are specified, firstName and lastName must be provided

SUCCESS RESPONSE - when the validation passes and a user is created successfully, return `201` with a payload including user and profile data:

```json
{
    "status": "success",
    "data": {
      "user": {
            "id": 0,
            "email": "string",
            "cohortId": 0,
            "role": "string",
            "firstName": "string",
            "lastName": "string",
            "bio": "string",
            "githubUrl": "string"
        }
    }
}
```

BAD REQUEST RESPONSE (400) should be sent in the following cases:

- when email is missing; error message = “Email is required”
- when email format is invalid; error message = “Email format invalid”
- when email is already in use; error message = “Email is already in use”
- when password is missing; error message = “Password is required”
- when password is < 8 characters; or doesn’t have at least 1 upper case and at least 1 number and at least 1 special character, then error message = “Password must contain at least one upper case character, at least one number, at least one special character and not be less than 8 characters in length.

BAD REQUEST RESPONSE PAYLOAD must have this format:

```json
{
    "status": "error",
    "data": {
        "error": "error message"
    }
}
```

**Database Changes**

None needed; all validation logic done in code.

**Frontend**

On clicking submit:

- Check that both fields have a length > 0
- Check that the email input is a valid email address
- Check that password matches the conditions in the epic:
- If the password field fails validation, show the below message:
    - “Password must contain at least one uppercase letter, one number, one special character and be at least 8 characters long.“
- If the email field fails validation, show the below message:
    - “Email address must be in a valid format.“
- The message should display immediately below the relevant field in a red coloured font
- If client-side validation passes but the server still responds with an error message, that error message should be displayed directly below the submit button in a red font

**Comment by vherus** [comment]
Break this backlog item down into individual Todo tasks in the Todo column. Each task should be a focused, single unit of work

**Comment by angustownsley** [comment]
I think a small database change is required to implement this. The firstName and lastName fields are currently not nullable in the database, and are not guaranteed to be provided immediately upon account creation. With this being the case, we can't send the success response as written here. Are you open to making these nullable?

**Comment by vherus** [comment]
https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=204-8131&t=Jwqcm4e3YIgfI7ax-0

**Comment by MyrtheDullaart** [comment]
For creating a profile, the missing steps (step 3 and 4) need to be implemented.

- Firstname and and lastname should be required.
- Username and mobile should be added to the profile model
- The github url should be changed to Github username

**Comment by angustownsley** [comment]
-Controller must return proper error when trying to create a new user without  "email" OR "password"

/users POST:{
"email": "example@example.com"
}
should return an error if email OR password are missing and NOT crash the server

Response: status = 400
```json
{
  "status": "string",
       "data": {
         "error": "string"
   }
}
```

The response In case of succesfull user creation should be:

Response: status = 201

```json

{
"status": "success",
      "data": {
          "user": {
                "id": 0,
                "email": "string",
                "cohortId": 0,
                "role": "string",
                "firstName": "string",
                "lastName": "string",
                "bio": "string",
                "githubUrl": "string"
            }
      }
}
```

-Email and password must be checked for validity

-Check email string for valid email format
-Check password's validity (Must contain: > 8 characters, at least one uppercase letter, one number and one special character)
Checking validity must be added in the user controller.

If invalid inputs are detected an error should be returned

Response: status = 400
```json
{
 "status": "error",
    "data": {
        "error": "error message"
    }
}
```

-Update DB schema so that firstName and lastName are nullable.
