### ISSUE TITLE
Update Patch Endpoint to allow users to update their own profile

### ISSUE THREAD

**Issue by angustownsley** [boolean-uk/team-dev-client-c12#41]
This will require updating the controller and domain quite significantly, to ensure that all updatable fields can be updated.

This will also require a small change to the way the auth middleware is set up, perhaps creating a new one that just adds if the user is a teacher to the request, rather than rejecting the request if they are not one, as Users must be able to update their own profile details.

Documentation will also need to be updated to reflect any changes to the request and response structure.

**Comment by MrStashy** [comment]
Teachers should be able ot change everything except a user's password (unless they are the logged in user)
