### ISSUE TITLE
BACKEND: Search for student by name endpoint

### ISSUE THREAD

**Issue by MrStashy** [boolean-uk/team-dev-client-c12#68]

**Comment by vherus** [comment]
Move to query parameter of getAll route

**Comment by homonoviscoding** [comment]
I have implemented a new route for the search by name endpoint using the branch: Mama#68-user-search-functionality. Feel free to checkout the new requirement asked by Lewis which consists of deleting the searchUser route and make sure the request happens in the getAll. @MyrtheDullaart
